openapi: 3.0.3
info:
  title: Messagerie ARC MAIL API
  description: API pour Arc Mail.
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
    description: Serveur de développement
paths:
  /messages:
    get:
      summary: Récupérer les messages
      description: Récupère une liste de messages, avec des options de filtre par dossier, tag, ou état.
      parameters:
        - name: folderId
          in: query
          description: ID du dossier (Inbox, Sent, etc.)
          schema:
            type: string
        - name: tag
          in: query
          description: Filtrer par tag
          schema:
            type: string
        - name: followed
          in: query
          description: Filtrer les messages suivis
          schema:
            type: boolean
      responses:
        200:
          description: Liste des messages récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
        400:
          description: Requête invalide
  /messages/{messageId}:
    get:
      summary: Récupérer les détails d’un message
      parameters:
        - name: messageId
          in: path
          required: true
          description: ID unique du message
          schema:
            type: string
      responses:
        200:
          description: Détails du message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        404:
          description: Message introuvable
components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: string
        sender:
          type: string
        recipients:
          type: array
          items:
            type: string
        subject:
          type: string
        content:
          type: string
        status:
          type: string
          enum: [read, unread, followed]
        createdAt:
          type: string
          format: date-time
